---
name: Python Linting and Type Checking

on:
  push:
    branches: ['main', 'python']
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/python-lint.yml'
  pull_request:
    branches: ['main', 'python']
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install dependencies
        run: uv sync

      - name: Lint with ruff
        run: uv run ruff check .

      - name: Format check with ruff
        run: uv run ruff format --check .

      - name: Type check with ty
        run: uv run ty check .
